# Generated by Django 5.2.14 on 2026-05-22 22:20

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва події')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('event_type', models.CharField(choices=[('morning', '🎭 Ранок / Свято'), ('open_door', '🚪 День відкритих дверей'), ('meeting', '👥 Батьківські збори'), ('competition', '🏆 Конкурс'), ('workshop', '🎨 Майстер-клас'), ('excursion', '🚌 Екскурсія'), ('sport', '⚽ Спортивна подія'), ('other', '📌 Інше')], default='other', max_length=20, verbose_name='Тип події')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Опис')),
                ('start_date', models.DateTimeField(verbose_name='Початок (дата і час)')),
                ('end_date', models.DateTimeField(blank=True, help_text='Залиште порожнім якщо подія однієї дати.', null=True, verbose_name='Закінчення')),
                ('location', models.CharField(blank=True, default='ЗДО №52, м. Рівне', max_length=200, verbose_name='Місце проведення')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Зображення')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='groups.group', verbose_name='Конкретна група (якщо подія тільки для однієї)')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
                'ordering': ['start_date'],
            },
        ),
    ]
