# Generated by Django 5.2.14 on 2026-06-01 22:59

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_seed_sample_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='Опис'),
        ),
    ]
