# Generated by Django 5.2.14 on 2026-06-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='Код (slug)')),
                ('name', models.CharField(help_text='Можна з емодзі на початку, напр. «🎭 Ранок / Свято».', max_length=120, verbose_name='Назва')),
                ('color', models.CharField(default='#7B8AA5', max_length=7, verbose_name='Колір (HEX)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип події',
                'verbose_name_plural': 'Типи подій',
                'ordering': ['order', 'id'],
            },
        ),
    ]
