# Generated by Django 5.2.14 on 2026-05-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('icon', models.CharField(blank=True, default='bi-folder-fill', help_text='Назва класу з Bootstrap Icons, наприклад: bi-people-fill, bi-balloon-fill.', max_length=80, verbose_name='Іконка (Bootstrap Icons)')),
                ('color', models.CharField(blank=True, default='#4A90E2', help_text='Колір заголовка секції на сторінці галереї. Наприклад: #4A90E2.', max_length=7, verbose_name='Колір (HEX)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категорія альбомів',
                'verbose_name_plural': 'Категорії альбомів',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Виберіть розділ галереї, де показуватиметься альбом (якщо порожньо — показуватиметься у блоці «Інше»).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='gallery.gallerycategory', verbose_name='Категорія'),
        ),
    ]
