# Generated by Django 5.2.15 on 2026-06-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Напр. «Музична зала», «Спортивний майданчик».', max_length=150, verbose_name='Назва зупинки')),
                ('description', models.TextField(blank=True, help_text='Короткий розповідний опис локації.', verbose_name='Опис')),
                ('image', models.ImageField(upload_to='tour/', verbose_name='Фото')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Зупинка туру',
                'verbose_name_plural': 'Віртуальний тур (зупинки)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
