# Generated by Django 5.2.14 on 2026-05-18 20:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0002_alter_specialist_id_alter_specialistalbum_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistpage',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Розширений опис напрямку: програми, тема, методи роботи тощо.', verbose_name='Опис діяльності (під картками спеціалістів)'),
        ),
        migrations.AddField(
            model_name='specialistpage',
            name='theme_period',
            field=models.CharField(blank=True, help_text='Наприклад: 2022–2027 роки', max_length=50, verbose_name='Період'),
        ),
        migrations.AddField(
            model_name='specialistpage',
            name='theme_text',
            field=models.TextField(blank=True, verbose_name='Текст теми'),
        ),
        migrations.AddField(
            model_name='specialistpage',
            name='theme_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Заголовок науково-методичної теми'),
        ),
    ]
