# Generated by Django 5.2.14 on 2026-05-18 22:00

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('specialists', '0003_specialistpage_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок розділу')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Опис розділу')),
                ('icon', models.CharField(default='bi-lightning-fill', help_text='Наприклад: bi-snow, bi-sun, bi-bicycle, bi-heart-pulse.', max_length=80, verbose_name='Іконка (Bootstrap Icons)')),
                ('accent', models.CharField(choices=[('primary', 'Синій'), ('success', 'Зелений'), ('warning', 'Помаранчевий'), ('danger', 'Червоний'), ('info', 'Бірюзовий'), ('purple', 'Фіолетовий'), ('pink', 'Рожевий')], default='primary', max_length=20, verbose_name='Колір акценту')),
                ('kind', models.CharField(choices=[('info', 'Інформаційна (з інлайн-фото)'), ('event', 'Подія (посилання на альбом / новину)')], default='info', max_length=10, verbose_name='Тип розділу')),
                ('link_news_slug', models.SlugField(blank=True, help_text='Slug існуючої новини (наприклад: svyato-oseni-u-zdo-52).', verbose_name='Slug новини')),
                ('link_external_url', models.URLField(blank=True, verbose_name='Зовнішнє посилання')),
                ('link_label', models.CharField(blank=True, default='Переглянути фотоальбом', max_length=100, verbose_name='Текст кнопки-посилання')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('link_album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.galleryalbum', verbose_name='Альбом у галереї')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='specialists.specialistpage', verbose_name='Сторінка')),
            ],
            options={
                'verbose_name': 'Розділ сторінки спеціаліста',
                'verbose_name_plural': 'Розділи сторінок спеціалістів',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistPagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='specialists/sections/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Підпис')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='specialists.specialistpagesection', verbose_name='Розділ')),
            ],
            options={
                'verbose_name': 'Фото розділу спеціаліста',
                'verbose_name_plural': 'Фото розділів спеціалістів',
                'ordering': ['order', 'id'],
            },
        ),
    ]
