# Generated by Django 5.2.14 on 2026-06-01 22:59

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0004_specialistpagesection_specialistpagephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='bio',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='Біографія / опис діяльності'),
        ),
        migrations.AlterField(
            model_name='specialistpage',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Розширений опис напрямку: програми, тема, методи роботи тощо.', verbose_name='Опис діяльності (під картками спеціалістів)'),
        ),
        migrations.AlterField(
            model_name='specialistpagesection',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='Опис розділу'),
        ),
    ]
