# Generated by Django 5.2.14 on 2026-05-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentsAdaptationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name="Підпис (необов'язково)")),
                ('image', models.ImageField(upload_to='parents/adaptation/', verbose_name='Фото')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': '03. Фото адаптації',
                'verbose_name_plural': '03. Фото адаптації',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParentsAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Підпис під зображенням. Можна залишити порожнім.', max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='parents/announcements/', verbose_name='Зображення')),
                ('link', models.URLField(blank=True, help_text='Якщо вказано — зображення буде клікабельне.', verbose_name='Посилання (за бажанням)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': '01. Оголошення (батькам)',
                'verbose_name_plural': '01. Оголошення (батькам)',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParentsDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Назва')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Короткий опис')),
                ('link_type', models.CharField(choices=[('external', 'Зовнішнє посилання (URL)'), ('page', 'Внутрішня сторінка (slug)'), ('file', 'Файл для завантаження')], default='external', max_length=20, verbose_name='Тип посилання')),
                ('external_url', models.URLField(blank=True, help_text='Заповнюйте, якщо тип = "Зовнішнє посилання".', verbose_name='Зовнішня URL-адреса')),
                ('internal_slug', models.SlugField(blank=True, help_text='Slug внутрішньої сторінки (Page). Заповнюйте, якщо тип = "Внутрішня сторінка".', verbose_name='Slug сторінки')),
                ('file', models.FileField(blank=True, help_text='Завантажуйте, якщо тип = "Файл".', null=True, upload_to='parents/documents/', verbose_name='Файл')),
                ('icon', models.CharField(default='bi-file-earmark-pdf', help_text='Назва класу Bootstrap Icon, наприклад: bi-file-earmark-pdf, bi-shield-check.', max_length=80, verbose_name='Іконка (Bootstrap Icons)')),
                ('accent', models.CharField(default='primary', help_text='primary, success, warning, danger, info, secondary', max_length=20, verbose_name='Колір акценту')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': '02. Документ (батькам)',
                'verbose_name_plural': '02. Документи (батькам)',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ParentsEnrollmentDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Назва документа')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Примітка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': '04. Документ для зарахування',
                'verbose_name_plural': '04. Документи для зарахування',
                'ordering': ['order', 'id'],
            },
        ),
    ]
