# Generated by Django 5.2.14 on 2026-05-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_parentsadaptationphoto_parentsannouncement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentsApplicationSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Зразок заяви', max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='parents/samples/', verbose_name='Фото зразка')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Підпис під фото')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': '05. Зразок заяви',
                'verbose_name_plural': '05. Зразки заяв',
                'ordering': ['order', '-id'],
            },
        ),
    ]
