# Generated by Django 5.2.14 on 2026-05-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_parentsapplicationsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pages/gallery/', verbose_name='Зображення')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Підпис')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.page', verbose_name='Сторінка')),
            ],
            options={
                'verbose_name': 'Зображення сторінки',
                'verbose_name_plural': 'Зображення сторінок',
                'ordering': ['order', 'id'],
            },
        ),
    ]
