# Generated by Django 5.2.14 on 2026-05-18 20:17

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Прізвище, імʼя, по батькові')),
                ('position', models.CharField(max_length=200, verbose_name='Посада')),
                ('photo', models.ImageField(blank=True, help_text='Якщо порожньо — використовується аватар-плейсхолдер.', null=True, upload_to='staff/', verbose_name='Фото')),
                ('education', models.CharField(blank=True, help_text='Наприклад: вища; вища, спеціаліст вищої категорії.', max_length=300, verbose_name='Освіта')),
                ('experience', models.CharField(blank=True, help_text='Наприклад: стаж педагогічної роботи 36 років.', max_length=200, verbose_name='Стаж')),
                ('category', models.CharField(blank=True, max_length=300, verbose_name='Категорія / Звання')),
                ('awards', models.TextField(blank=True, help_text='Кожна нагорода — з нового рядка. Будуть показані як список.', verbose_name='Нагороди та звання')),
                ('bio', markdownx.models.MarkdownxField(blank=True, verbose_name='Біографія / Додаткова інформація')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('reception_hours', models.CharField(blank=True, max_length=200, verbose_name='Години прийому')),
                ('is_featured', models.BooleanField(default=False, help_text='Виділена картка показується першою у великому форматі.', verbose_name='Виділити (директор/головна особа)')),
                ('accent_color', models.CharField(default='primary', help_text='primary, success, warning, danger, info, purple', max_length=20, verbose_name='Колір акценту')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Член керівництва',
                'verbose_name_plural': 'Керівництво / Адміністрація',
                'ordering': ['order', 'id'],
            },
        ),
    ]
