# Generated by Django 5.2.14 on 2026-05-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='detail_url',
            field=models.CharField(blank=True, help_text='Наприклад: /specialists/psychologist/ або /specialists/medical/', max_length=300, verbose_name='Посилання на повну сторінку'),
        ),
    ]
