# Generated by Django 5.2.14 on 2026-05-21 08:51

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_staffmember_detail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва категорії')),
                ('description', models.TextField(help_text='Стисло: умови присвоєння, стаж тощо.', verbose_name='Опис / вимоги')),
                ('icon', models.CharField(default='bi-mortarboard', help_text='Наприклад: bi-mortarboard, bi-star-fill, bi-trophy-fill.', max_length=80, verbose_name='Іконка (Bootstrap Icons)')),
                ('color', models.CharField(choices=[('cat-1', '🟢 Зелений (Спеціаліст)'), ('cat-2', '🔵 Блакитний (II категорія)'), ('cat-3', '🔷 Синій (I категорія)'), ('cat-4', '🟣 Фіолетовий (Вища)')], default='cat-1', max_length=10, verbose_name='Колір')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': '03. Кваліфікаційна категорія',
                'verbose_name_plural': '03. Кваліфікаційні категорії',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttestationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Назва документа')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Короткий опис / уточнення')),
                ('category', models.CharField(default='Документ', help_text='Коротка мітка: Наказ, Графік, Список, Строки, Перелік тощо.', max_length=50, verbose_name='Тип документа')),
                ('url', models.URLField(help_text='URL у Google Drive / Docs або на ваш сайт.', verbose_name='Посилання на документ')),
                ('icon', models.CharField(default='bi-file-earmark-pdf-fill', help_text='Наприклад: bi-file-earmark-pdf-fill, bi-calendar-event-fill.', max_length=80, verbose_name='Іконка (Bootstrap Icons)')),
                ('accent', models.CharField(choices=[('primary', 'Синій'), ('success', 'Зелений'), ('warning', 'Помаранчевий'), ('info', 'Блакитний'), ('purple', 'Фіолетовий'), ('danger', 'Червоний')], default='primary', max_length=20, verbose_name='Колір акценту')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': '01. Документ атестації',
                'verbose_name_plural': '01. Документи атестаційної комісії',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttestationLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Назва нормативного документа')),
                ('url', models.URLField(blank=True, help_text='Якщо є — назва стане клікабельною.', verbose_name='Посилання (необовʼязкове)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': '04. Нормативний документ',
                'verbose_name_plural': '04. Нормативна база атестації',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttestationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_lead', models.TextField(default='Атестація — це система заходів, спрямована на всебічне комплексне оцінювання педагогічної діяльності, за результатами якої присвоюється кваліфікаційна категорія.', verbose_name='Підзаголовок під H1 (hero)')),
                ('intro_html', markdownx.models.MarkdownxField(blank=True, help_text='Підтримує форматування. Зʼявляється угорі сторінки.', verbose_name='Вступний блок (синій, ліворуч)')),
                ('docs_section_subtitle', models.CharField(default='2025–2026 навчальний рік', max_length=200, verbose_name='Підзаголовок секції документів')),
                ('contact_title', models.CharField(default='Маєте запитання щодо атестації?', max_length=200, verbose_name='Заголовок підказки про контакти')),
                ('contact_html', markdownx.models.MarkdownxField(blank=True, default='<p>Звертайтеся до <strong>вихователя-методиста</strong> закладу — він допоможе з оформленням документів, поясненням етапів і термінів.</p>', verbose_name='Текст підказки про контакти (жовтий блок)')),
            ],
            options={
                'verbose_name': '00. Налаштування сторінки',
                'verbose_name_plural': '00. Налаштування сторінки атестації',
            },
        ),
        migrations.CreateModel(
            name='AttestationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Назва етапу')),
                ('description', models.TextField(blank=True, verbose_name='Пояснення')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок (= номер кроку)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': '02. Етап атестації',
                'verbose_name_plural': '02. Етапи проведення атестації',
                'ordering': ['order', 'id'],
            },
        ),
    ]
