# Generated by Django 5.2.14 on 2026-06-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_seed_attestation_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=600, unique=True, verbose_name='Endpoint')),
                ('p256dh', models.CharField(max_length=200, verbose_name='Ключ p256dh')),
                ('auth', models.CharField(max_length=100, verbose_name='Ключ auth')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Підписано')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Push-підписка',
                'verbose_name_plural': 'Push-підписки',
                'ordering': ['-created_at'],
            },
        ),
    ]
