# Generated by Django 5.2.14 on 2026-06-01 22:59

import django.db.models.deletion
import markdownx.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationsettings',
            name='contact_html',
            field=markdownx.models.MarkdownxField(blank=True, default='<p>Звертайтеся до <strong>вихователя-методиста</strong> закладу — він допоможе з оформленням документів, поясненням етапів і термінів.</p>', verbose_name='Текст підказки про контакти (жовтий блок)'),
        ),
        migrations.AlterField(
            model_name='attestationsettings',
            name='intro_html',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Підтримує форматування. Зʼявляється угорі сторінки.', verbose_name='Вступний блок (синій, ліворуч)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='bio',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='Біографія / Додаткова інформація'),
        ),
        migrations.CreateModel(
            name='HistoricalPage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('content', markdownx.models.MarkdownxField(verbose_name='Контент')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Зображення')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата оновлення')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Сторінка',
                'verbose_name_plural': 'historical Сторінки',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
