# Generated by Django 5.2.14 on 2026-06-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_attestationsettings_contact_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='video',
            field=models.FileField(blank=True, help_text='MP4/WebM. Якщо задано — програється замість зображення (зображення стає постером).', upload_to='slider/videos/', verbose_name='Відео-фон (необовʼязково)'),
        ),
    ]
