# Generated by Django 5.2.14 on 2026-06-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_slider_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='topics',
            field=models.JSONField(blank=True, default=list, help_text='Список тем (news, events). Порожній список = отримує всі сповіщення.', verbose_name='Теми підписки'),
        ),
    ]
