# Generated by Django 5.2.14 on 2026-06-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_pushsubscription_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_moderate_reviews', models.BooleanField(default=False, help_text='Якщо увімкнено — нові відгуки автоматично перевіряються ШІ: коректні публікуються одразу, підозрілі (лайка, погрози тощо) відкладаються на ручну модерацію.', verbose_name='Авто-модерація відгуків ШІ')),
            ],
            options={
                'verbose_name': 'Налаштування ШІ',
                'verbose_name_plural': 'Налаштування ШІ',
            },
        ),
    ]
