# Generated by Django 5.2.15 on 2026-06-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_aisettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50, verbose_name='Тип контенту')),
                ('object_id', models.CharField(max_length=100, verbose_name='ID обʼєкта')),
                ('text_hash', models.CharField(help_text='MD5 хеш для інвалідації при зміні тексту', max_length=64, verbose_name='Хеш тексту')),
                ('embedding', models.JSONField(help_text='Список float (напр. 768 значень)', verbose_name='Вектор')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Вектор пошуку',
                'verbose_name_plural': 'Вектори пошуку',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='main_search_content_942fb0_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
