# Generated by Django 5.2.15 on 2026-06-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Запитання')),
                ('sources_found', models.BooleanField(default=False, verbose_name='Знайдено інформацію на сайті')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Лог чату',
                'verbose_name_plural': 'Логи чатів',
                'ordering': ['-created_at'],
            },
        ),
    ]
