# Generated by Django 5.2.14 on 2026-05-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circledocument',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Документ гурткової роботи', 'verbose_name_plural': 'Документи гурткової роботи'},
        ),
        migrations.AlterField(
            model_name='circle',
            name='color',
            field=models.CharField(default='#4A90E2', max_length=7, verbose_name='Колір (HEX)'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='icon',
            field=models.CharField(default='bi-star', max_length=50, verbose_name='Іконка (Bootstrap Icons)'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='leader',
            field=models.CharField(max_length=200, verbose_name='Керівник гуртка'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='schedule',
            field=models.CharField(blank=True, max_length=200, verbose_name='Розклад занять'),
        ),
        migrations.AlterField(
            model_name='circledocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
