# Generated by Django 5.2.14 on 2026-06-01 22:59

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_alter_circledocument_options_alter_circle_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='description',
            field=markdownx.models.MarkdownxField(verbose_name='Опис діяльності'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='goal',
            field=markdownx.models.MarkdownxField(verbose_name='Мета та завдання'),
        ),
    ]
