# Generated by Django 5.2.14 on 2026-06-03 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_alter_circle_description_alter_circle_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='cover',
            field=models.ImageField(blank=True, upload_to='circles/', verbose_name='Обкладинка (необовʼязково)'),
        ),
        migrations.AddField(
            model_name='circle',
            name='duration',
            field=models.CharField(blank=True, help_text='напр. «25–35 хв»', max_length=100, verbose_name='Тривалість заняття'),
        ),
        migrations.AddField(
            model_name='circle',
            name='format',
            field=models.CharField(blank=True, help_text='напр. «Групові заняття, до 10 дітей»', max_length=120, verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='circle',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендований (виділити)'),
        ),
        migrations.AddField(
            model_name='circle',
            name='price',
            field=models.CharField(blank=True, default='Безкоштовно', max_length=120, verbose_name='Вартість'),
        ),
        migrations.AddField(
            model_name='circle',
            name='tagline',
            field=models.CharField(blank=True, help_text='Одне речення для картки, напр. «Перші слова англійською через гру».', max_length=300, verbose_name='Короткий слоган'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='schedule',
            field=models.CharField(blank=True, max_length=200, verbose_name='Розклад (коротко)'),
        ),
        migrations.CreateModel(
            name='CircleBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi-check-circle', max_length=50, verbose_name='Іконка (Bootstrap Icons)')),
                ('title', models.CharField(max_length=150, verbose_name='Що розвиває')),
                ('text', models.CharField(blank=True, max_length=300, verbose_name='Пояснення')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='circles.circle', verbose_name='Гурток')),
            ],
            options={
                'verbose_name': 'Перевага гуртка',
                'verbose_name_plural': 'Що розвиває (переваги)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CircleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=40, verbose_name='День')),
                ('time', models.CharField(max_length=40, verbose_name='Час')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='Група / примітка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='circles.circle', verbose_name='Гурток')),
            ],
            options={
                'verbose_name': 'Заняття у розкладі',
                'verbose_name_plural': 'Розклад занять',
                'ordering': ['order', 'id'],
            },
        ),
    ]
