# Generated by Django 5.2.14 on 2026-06-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_dislikes_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Якщо заповнено — публічно показується під відгуком як офіційна відповідь закладу.', verbose_name='Відповідь адміністрації'),
        ),
    ]
