# Generated by Django 5.2.14 on 2026-06-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_admin_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ai_moderation',
            field=models.CharField(blank=True, max_length=500, verbose_name='Вердикт ШІ-модерації'),
        ),
    ]
