# Generated by Django 5.2.14 on 2026-05-22 22:20

import markdownx.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('icon', models.CharField(blank=True, default='bi-question-circle-fill', max_length=80, verbose_name='Іконка (Bootstrap Icons)')),
                ('color', models.CharField(blank=True, default='#4A90E2', max_length=7, verbose_name='Колір (HEX)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категорія FAQ',
                'verbose_name_plural': 'Категорії FAQ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400, verbose_name='Питання')),
                ('answer', markdownx.models.MarkdownxField(help_text='Підтримує форматування: жирний, посилання тощо.', verbose_name='Відповідь')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='faq.faqcategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання-відповіді',
                'ordering': ['order', 'id'],
            },
        ),
    ]
