# Generated by Django 5.2.14 on 2026-05-23 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_seed_sample_faqs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQQuestionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Імʼя батька / опікуна')),
                ('phone', models.CharField(max_length=50, verbose_name='Контактний телефон')),
                ('question', models.TextField(max_length=2000, verbose_name='Текст запитання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Надіслано')),
                ('is_handled', models.BooleanField(default=False, help_text='Поставте галочку коли вже зателефонували / відповіли — тоді запитання сховається зі списку нових.', verbose_name='✅ Оброблено (відповіли)')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обробки')),
                ('admin_note', models.TextField(blank=True, help_text='Коротко: що відповіли / коли передзвонили / результат.', verbose_name='Нотатка адміністратора')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_faq_questions', to=settings.AUTH_USER_MODEL, verbose_name='Хто обробив')),
            ],
            options={
                'verbose_name': 'Запитання від відвідувача',
                'verbose_name_plural': 'Запитання від батьків (надіслані з сайту)',
                'ordering': ['is_handled', '-created_at'],
                'indexes': [models.Index(fields=['is_handled', 'created_at'], name='faq_faqques_is_hand_6f6848_idx')],
            },
        ),
    ]
