# Generated by Django 5.2.14 on 2026-06-01 22:59

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_submission_status_callback'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='faqquestionsubmission',
            new_name='faq_faqques_status_aa410a_idx',
            old_name='faq_faqques_status_idx',
        ),
        migrations.RenameIndex(
            model_name='faqquestionsubmission',
            new_name='faq_faqques_callbac_7450ec_idx',
            old_name='faq_faqques_callbck_idx',
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=markdownx.models.MarkdownxField(help_text='Підтримує форматування: жирний, посилання тощо.', verbose_name='Відповідь'),
        ),
    ]
