# Generated by Django 5.2.14 on 2026-06-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_rename_faq_faqques_status_idx_faq_faqques_status_aa410a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='likes',
            field=models.PositiveIntegerField(default=0, help_text='Скільки відвідувачів позначили це питання корисним.', verbose_name='👍 Корисно'),
        ),
    ]
