# Generated by Django 5.2.14 on 2026-05-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('breakfast', models.TextField(blank=True, verbose_name='🥣 Сніданок')),
                ('second_breakfast', models.TextField(blank=True, help_text='Часто це фрукт або сік. Необовʼязково.', verbose_name='🍎 II сніданок')),
                ('lunch', models.TextField(blank=True, verbose_name='🍲 Обід')),
                ('snack', models.TextField(blank=True, verbose_name='🥨 Полуденок')),
                ('dinner', models.TextField(blank=True, help_text='Для чергових груп (12 годин). Необовʼязково.', verbose_name='🥛 Вечеря')),
                ('note', models.CharField(blank=True, help_text='Наприклад: «Святкове меню до Дня матері» або позначення алергенів.', max_length=300, verbose_name='Примітка дня')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Меню на день',
                'verbose_name_plural': 'Денні меню',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='menu_dailym_date_6f5f50_idx')],
            },
        ),
    ]
