# Generated by Django 5.2.14 on 2026-06-01 22:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, "П'ятниця"), (5, 'Субота'), (6, 'Неділя')], unique=True, verbose_name='День тижня')),
                ('breakfast', models.TextField(blank=True, verbose_name='🥣 Сніданок')),
                ('second_breakfast', models.TextField(blank=True, verbose_name='🍎 II сніданок')),
                ('lunch', models.TextField(blank=True, verbose_name='🍲 Обід')),
                ('snack', models.TextField(blank=True, verbose_name='🥨 Полуденок')),
                ('dinner', models.TextField(blank=True, verbose_name='🥛 Вечеря')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Примітка')),
                ('is_active', models.BooleanField(default=True, help_text='Якщо вимкнено — цей день шаблону не показується.', verbose_name='Використовувати як основу')),
            ],
            options={
                'verbose_name': 'Шаблон меню (день тижня)',
                'verbose_name_plural': '📋 Шаблон меню (тиждень-основа)',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDailyMenu',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('breakfast', models.TextField(blank=True, verbose_name='🥣 Сніданок')),
                ('second_breakfast', models.TextField(blank=True, help_text='Часто це фрукт або сік. Необовʼязково.', verbose_name='🍎 II сніданок')),
                ('lunch', models.TextField(blank=True, verbose_name='🍲 Обід')),
                ('snack', models.TextField(blank=True, verbose_name='🥨 Полуденок')),
                ('dinner', models.TextField(blank=True, help_text='Для чергових груп (12 годин). Необовʼязково.', verbose_name='🥛 Вечеря')),
                ('note', models.CharField(blank=True, help_text='Наприклад: «Святкове меню до Дня матері» або позначення алергенів.', max_length=300, verbose_name='Примітка дня')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Оновлено')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Меню на день',
                'verbose_name_plural': 'historical Денні меню',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
