# Generated by Django 5.2.14 on 2026-06-01 22:59

import django.db.models.deletion
import markdownx.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Лише для статусу «Заплановано»: дата і час автоматичної появи на сайті.', null=True, verbose_name='Опублікувати о'),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', '📝 Чернетка'), ('published', '✅ Опубліковано'), ('scheduled', '⏰ Заплановано')], default='published', help_text='Чернетка — не видно на сайті. Заплановано — зʼявиться у вказану дату.', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, editable=False, verbose_name='Опубліковано'),
        ),
        migrations.CreateModel(
            name='HistoricalNews',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('content', markdownx.models.MarkdownxField(verbose_name='Контент')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Зображення')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата публікації')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата оновлення')),
                ('status', models.CharField(choices=[('draft', '📝 Чернетка'), ('published', '✅ Опубліковано'), ('scheduled', '⏰ Заплановано')], default='published', help_text='Чернетка — не видно на сайті. Заплановано — зʼявиться у вказану дату.', max_length=12, verbose_name='Статус')),
                ('publish_at', models.DateTimeField(blank=True, help_text='Лише для статусу «Заплановано»: дата і час автоматичної появи на сайті.', null=True, verbose_name='Опублікувати о')),
                ('is_published', models.BooleanField(default=True, editable=False, verbose_name='Опубліковано')),
                ('views', models.IntegerField(default=0, verbose_name='Перегляди')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='news.newscategory', verbose_name='Категорія')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Новина',
                'verbose_name_plural': 'historical Новини',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
