# Generated by Django 5.2.15 on 2026-06-08 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=150, verbose_name="Ім'я дитини")),
                ('child_birth_date', models.DateField(verbose_name='Дата народження дитини')),
                ('parent_name', models.CharField(max_length=150, verbose_name="Ім'я батька / матері")),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('desired_start', models.CharField(blank=True, help_text='Напр. «вересень 2026» або конкретна дата.', max_length=100, verbose_name='Бажаний початок відвідування')),
                ('note', models.TextField(blank=True, verbose_name='Додаткова інформація')),
                ('status', models.CharField(choices=[('new', '🆕 Нова'), ('processing', '👀 В обробці'), ('approved', '✅ Схвалено'), ('rejected', '🚫 Відхилено'), ('done', '🏁 Завершено')], default='new', max_length=12, verbose_name='Статус')),
                ('admin_note', models.TextField(blank=True, verbose_name='Нотатка адміністрації')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата опрацювання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Опрацював')),
            ],
            options={
                'verbose_name': 'Заявка на зарахування',
                'verbose_name_plural': 'Заявки на зарахування',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='enrollment__status_e0124a_idx')],
            },
        ),
    ]
